name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.API }}" \
          --data '{
            "query": "mutation ($serviceId: ID!, $branch: String!) { syncServiceToBranch(input: { serviceId: $serviceId, branch: $branch }) { service { id } } }",
            "variables": {
              "serviceId": "leaderboard",
              "branch": "main"
            }
          }'
