name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: true
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_USER: ${{ secrets.MONGODB_USER }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10","3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        chmod a+x build.sh
        ./build.sh
    - name: Run tests
      run: |
        python -m unittest discover app/